name: drupal-php{{php_version}}
services:
  drupal:
    image: xenyo/drupal:php{{php_version}}
    depends_on:
      - mariadb
    hostname: drupal-php{{php_version}}
    ports:
      - ${SSH_PORT:-22}:22
      - ${APACHE_PORT:-80}:80
    volumes:
      - ~/.ssh:/mnt/.ssh:ro
      - www:/var/www

  mariadb:
    image: mariadb:10
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
    volumes:
      - db:/var/lib/mysql

volumes:
  www:
  db:
